### ISSUE TITLE
com.crimsonhexagon.rsm.redisson.RedissonSessionClient.load Incompatible session class found in redis for session [_rsm_1E2ECEB65C1F6585EEF6FE7E1C67F424]: class com.crimsonhexagon.rsm.RedisSession

### ISSUE THREAD

**Issue by monzavimm** [chexagon/redis-session-manager#11]
com.crimsonhexagon.rsm.redisson.RedissonSessionClient.load Incompatible session class found in redis for session [_rsm_1E2ECEB65C1F6585EEF6FE7E1C67F424]: class com.crimsonhexagon.rsm.RedisSession
why?
there is any idea?

**Comment by amuxtux** [comment]
I am also getting the same error and session is regenerating every time

**Comment by monzavimm** [comment]
is there any support for this????

**Comment by scubasau** [comment]
Sorry, I didn't have notifications enabled for this project and wasn't aware people outside my employment were using it :)

Can you provide some more information about tomcat version and session manager configuration? The log message is a bit strange as the class logged as the object type is the same class that was just checked: https://github.com/chexagon/redis-session-manager/blob/master/src/main/java/com/crimsonhexagon/rsm/redisson/RedissonSessionClient.java#L60

**Comment by scubasau** [comment]
Please create a new ticket witht he above information if this issue recurs.
