### ISSUE TITLE
Publish to maven repository

### ISSUE THREAD

**Issue by gonzalad** [chexagon/redis-session-manager#18]
Perhaps I missed something but I didn't see this library in a public maven repo.
Could this be pushed in a public repo (i.e. maven central) ?
This would allow quicker adoption.

Thanks

**Comment by scubasau** [comment]
Sure, I can look into this. It appears this project has received more attention than I've been aware of! Time to re-enable github notifications!

**Comment by scubasau** [comment]
Release 2.2.0 has been pushed to central.
https://repo1.maven.org/maven2/com/crimsonhexagon/redis-session-manager/

**Comment by scubasau** [comment]
Note: if using the jar from central you'll need to add redisson and netty-transport-native-epoll to tomcat/lib as this is not the shaded jar.
