### ISSUE TITLE
Redis 3 Clustering

### ISSUE THREAD

**Issue by nothing2see** [chexagon/redis-session-manager#2]
Are there any plans to add in support for redis 3.0 clustering? We are migrating to a 6 node cluster (3 master, 3 slaves) with redis 3, and while we've had great success with this manager with a single node, we obviously get errors trying to add multiple masters/slaves.

**Comment by drawhan** [comment]
i hope too 

i really needed to me

**Comment by scubasau** [comment]
Hi. There are no current plans for redis 3 support but it is something that we will take another look at in the future.
