### ISSUE TITLE
endpoint config bug

### ISSUE THREAD

**Issue by hkkhchan** [chexagon/redis-session-manager#22]
I found the below not work
```
	<Manager className="com.crimsonhexagon.rsm.redisson.SingleServerSessionManager"
	endpoint="redis://localhost:6379"
	/> 
```
console will show hostname can't be null.
but this is work
```
	<Manager className="com.crimsonhexagon.rsm.redisson.SingleServerSessionManager"
	endpoint="localhost:6379"
	/>
```

**Comment by scubasau** [comment]
the `redis://` prefix is required for redisson 3.4.3+ (see issue #20). There has been no release with this version of redisson yet, so the README config applies only to master. Omitting the prefix as you specified will work for older redisson versions (all current RSM releases)
