### ISSUE TITLE
Error cause by java.io.NotSerializableException when setAttribute()

### ISSUE THREAD

**Issue by hkkhchan** [chexagon/redis-session-manager#23]
When I setAttribute(), the error occur. It seem like my object [MSRegEvent] is not serializable.
The error log is as below:

 5121 26-Oct-2017 17:50:12.255 嚴重 [ajp-nio-54500-exec-9] com.crimsonhexagon.rsm.RedisSessionManager.save Failed to save session [2746DDC0A4C51EBD01081AB9AA6F7738]
   5122  org.redisson.client.RedisException: Unexpected exception while processing command
   5123         at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:258)
   5124         at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:103)
   5125         at org.redisson.RedissonObject.get(RedissonObject.java:55)
   5126         at org.redisson.RedissonBucket.set(RedissonBucket.java:102)
   5127         at com.crimsonhexagon.rsm.redisson.RedissonSessionClient.save(RedissonSessionClient.java:45)
   5128         at com.crimsonhexagon.rsm.RedisSessionManager.save(RedisSessionManager.java:261)
   5129         at com.crimsonhexagon.rsm.RedisSession.saveOnChange(RedisSession.java:134)
   5130         at com.crimsonhexagon.rsm.RedisSession.setAttribute(RedisSession.java:91)
   5131         at org.apache.catalina.session.StandardSessionFacade.setAttribute(StandardSessionFacade.java:137)
....
 5179 Caused by: java.io.NotSerializableException: now.registration.model.MSRegEvent
   5180         at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
   5181         at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
   5182         at java.util.concurrent.ConcurrentHashMap.writeObject(ConcurrentHashMap.java:1413)
   5183         at sun.reflect.GeneratedMethodAccessor62.invoke(Unknown Source)
   5184         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   5185         at java.lang.reflect.Method.invoke(Method.java:497)
   5186         at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:988)
   5187         at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
   5188         at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
   5189         at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
   5190         at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
   5191         at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
   5192         at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
   5193         at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
   5194         at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
   5195         at org.redisson.codec.SerializationCodec$2.encode(SerializationCodec.java:58)

**Comment by scubasau** [comment]
This is expected: attributes added to the session need to be serializable
