### ISSUE TITLE
How to set the session expire time in this package?

### ISSUE THREAD

**Issue by rudolphzhong** [chexagon/redis-session-manager#27]
My java project show some problem when using this package to keep sessions. Session from my package will expire after about 1 minute, could you please check for me what the problem was? It was the problem about my tomcat setting, my redis setting, build setting about this package, or code?

**Comment by scubasau** [comment]
the session timeout is read from the context:
https://github.com/chexagon/redis-session-manager/blob/master/src/main/java/com/crimsonhexagon/rsm/RedisSessionManager.java#L138

typically this is done in `web.xml`, e.g.,
```
...
    <session-config>
        <session-timeout>480</session-timeout> <!-- in minutes -->
	</session-config>
...
```
for an 8 hour timeout
