### ISSUE TITLE
Update version of Redisson

### ISSUE THREAD

**Issue by nickptrvc** [chexagon/redis-session-manager#28]
Redisson 3.7.4 is out with a lot of fixes. Can we update this to use the latest version?

**Comment by scubasau** [comment]
3.7.5 came out yesterday so I've upgraded to this :) See https://github.com/chexagon/redis-session-manager/commit/cd8184ab0daf22d72bd67973246c499ece76b5f2

I have not yet tested the package (other than unit tests) so please open a new issue(s) should there be anything broken by the upgrade.

After I have time to test it in our dev/qa environments I'll push a new release to central.
