### ISSUE TITLE
Session manager is not working with tomcat 8.5.29

### ISSUE THREAD

**Issue by rudaym** [chexagon/redis-session-manager#29]
Tried to configure ElasticacheSessionManager with AWS redis engine 4.0.10. Though the session is getting created in redis (when I do keys *), tomcat is failing to use it. Here is my configuration.

Context.xml
<Manager className="com.crimsonhexagon.rsm.redisson.ElasticacheSessionManager"
        nodes="redis://tomcat-host-name.cache.amazonaws.com:6379"
        nodePollInterval="1000"
        sessionKeyPrefix=""
        saveOnChange="false"
        forceSaveAfterRequest="false"
        dirtyOnMutation="false"
        ignorePattern=".*\\.(ico|png|gif|jpg|jpeg|swf|css|js)$"
        maxSessionAttributeSize="-1"
        maxSessionSize="-1"
        allowOversizedSessions="false"
        masterConnectionPoolSize="100"
        slaveConnectionPoolSize="100"
        database="0"
        timeout="60000"
        pingTimeout="1000"
        retryAttempts="20"
        retryInterval="1000"
/>

Compiled the code and placed redis-session-manager-with-dependencies-2.2.2-SNAPSHOT.jar in TOMCAT_HOME/lib.

Following the stack trace in the tomcat log.

14-Aug-2018 16:46:57.055 SEVERE [ajp-nio-8009-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [RetriveLoginImageServlet] in context with path [] threw exception
 java.lang.NullPointerException
        at org.apache.catalina.session.StandardSession.isValid(StandardSession.java:675)
        at org.apache.catalina.connector.Request.doGetSession(Request.java:2976)
        at org.apache.catalina.connector.Request.getSession(Request.java:2429)
        at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:896)

Things are working fine if I download the latest version of redis server and use the in a standalone server instead of using AWS redis.

Any help around this would be really helpful.

**Comment by scubasau** [comment]
The artifacts that are pushed to maven-central are for tomcat 8.0.x. Preliminary (and untested) Tomcat 8.5.x support is in branch `tomcat-8.5`: https://github.com/chexagon/redis-session-manager/tree/tomcat-8.5.

If a build from that branch fails to work please open a new issue.
