### ISSUE TITLE
Tomcat7 Support

### ISSUE THREAD

**Issue by RomeLeader** [chexagon/redis-session-manager#3]
Any plans for Tomcat7 support? Is there anything that is problematic about running the instance with a tweak to the requirements for Tomcat7 (i.e. in the pom.xml)?

**Comment by scubasau** [comment]
Hi! Sorry for the super long delay in answering this issue. We don't currently have any plans to support Tomcat7 nor do I have any experience with attempting to run this under 7. 

If you do make any changes to support it please post here so that they can be documented for other users.
