### ISSUE TITLE
Failed to load session '123ADASSD123' from redis

### ISSUE THREAD

**Issue by tomcao** [chexagon/redis-session-manager#31]
Hello, I tried to apply Redis in my Java spring app. Sometimes I faced this error, then the user session will end, users are kicked out and asked to login again:
```
updateTotalAndAvg: asdsad-asdsadasd-12321321-11111-111111111 - [100000000,100000000000]
04-Oct-2018 08:29:17.995 SEVERE [http-nio-443-exec-13] com.crimsonhexagon.rsm.RedisSessionManager.findSession Failed to load session [51AF0DF158AAFAD3644E613039CE50EE] from redis
 org.redisson.client.RedisException: Unexpected exception while processing command
        at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:343)
        at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:170)
        at org.redisson.RedissonObject.get(RedissonObject.java:76)
```
Could you give me some suggestions for this?

**Comment by tomcao** [comment]
I've made all the classes "Serialize" as the solution given in the previous issue.

**Comment by scubasau** [comment]
Did implementing `Serializable` fix the issue? Or all classes are now serializable and you're still receiving it? If the latter, is there anything else in the logs about what the "unexpected exception" was?

**Comment by scubasau** [comment]
Closing stale issues
