### ISSUE TITLE
java.lang.ClassNotFoundException: com.crimsonhexagon.rsm.redisson.SingleServerSessionManager

### ISSUE THREAD

**Issue by ZulfuqarAliyev** [chexagon/redis-session-manager#32]
Hello. I have one issue. Adding redis-session-manager-with-dependencies-2.2.2-SNAPSHOT.jar to folder Tomcat/lib causes problems in production, that is why I added this jar file to war file WEB-INFO/lib folder via maven war plugin, but in this situation I got an error: java.lang.ClassNotFoundException: com.crimsonhexagon.rsm.redisson.SingleServerSessionManager.
Could you help me to solve this problem? Why compilator throws this exception?

**Comment by scubasau** [comment]
Due to tomcat's classloader, the session manager class must exist in a jar in tomcat/lib and not inside a web application. As such the problems caused by adding that jar to tomcat/lib should be addressed. If you can provide more info on this error in a new issue I will try to assist.
