### ISSUE TITLE
can not find jar file

### ISSUE THREAD

**Issue by monzavimm** [chexagon/redis-session-manager#8]
hi
i need pure redis-session-manager jar file to add in my library and can't find it
another thing is, if the redis-session-manager has a dependency such as jedis.jar and any other, please tell me 
thanks a lot

**Comment by futesat** [comment]
Hi monzavimm, you can compile it easily from src with maven. I did it yesterday and it works fine. I can send you the compiled jars if you want, it's up to you.

**Comment by roamerxv** [comment]
git pull the source , the use "mvn package" . int the targer floder， u'll find the redis-session-manager-with-dependencies-2.1.0.jar .

**Comment by monzavimm** [comment]
Unfortunately i cant compile it, my ide (itellij idea 16) throws exception, is it possible to upload jar file as a release??

**Comment by futesat** [comment]
redis-session-manager-2.1.0.jar:

https://github.com/futesat/redis-session-manager/blob/7cb4555e4480549a2c572a84e9aa678be72527b3/redis-session-manager-2.1.0.jar

redis-session-manager-with-dependencies-2.1.0.jar:

https://github.com/futesat/redis-session-manager/blob/7cb4555e4480549a2c572a84e9aa678be72527b3/redis-session-manager-with-dependencies-2.1.0.jar

**Comment by monzavimm** [comment]
thanks alot

**Comment by monzavimm** [comment]
throw SingleServerSessionManager

**Comment by monzavimm** [comment]
hi futesat
i put it in library and set the configuration but throw SingleServerSessionManager

<Manager className="com.crimsonhexagon.rsm.redisson.SingleServerSessionManager"
    endpoint="localhost:6379"
    sessionKeyPrefix="_rsm_"
    saveOnChange="false"
    forceSaveAfterRequest="false"
    dirtyOnMutation="false"
    connectionPoolSize="100"
    database="0"
    timeout="60000"
    pingTimeout="1000"
    retryAttempts="20"
    retryInterval="1000"
/>

thanks again
